export interface MealTemplate {
  name: string;
  description: string;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  category: "breakfast" | "lunch" | "dinner" | "snack";
  tags: string[]; // dietary: "vegetarian", "vegan", "pescatarian", "keto", "no_preference"
  ingredient_tags: string[];
  cuisine?: string;
  recipe?: {
    ingredients: { name: string; amount: string; unit: string; category: string }[];
    steps: string[];
    prep_time_min: number;
    cook_time_min: number;
  };
}

export const MEAL_TEMPLATES: MealTemplate[] = [
  // BREAKFAST (12 options)
  {
    name: "Scrambled Eggs & Toast",
    description:
      "Three scrambled eggs with two slices of whole wheat toast and a pat of butter.",
    calories: 420,
    protein_g: 25,
    carbs_g: 35,
    fat_g: 20,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["eggs", "wheat", "butter", "dairy"],
    recipe: {
      ingredients: [
        { name: "Eggs", amount: "3", unit: "large", category: "protein" },
        { name: "Whole wheat bread", amount: "2", unit: "slices", category: "grains" },
        { name: "Butter", amount: "1", unit: "tbsp", category: "dairy" },
        { name: "Salt", amount: "1", unit: "pinch", category: "pantry" },
        { name: "Black pepper", amount: "1", unit: "pinch", category: "pantry" },
      ],
      steps: [
        "Crack eggs into a bowl, add salt and pepper, whisk until combined.",
        "Heat butter in a non-stick pan over medium-low heat.",
        "Pour in eggs and stir gently with a spatula, forming soft curds.",
        "Remove from heat while still slightly wet — they'll finish cooking from residual heat.",
        "Toast the bread and serve alongside the eggs.",
      ],
      prep_time_min: 3,
      cook_time_min: 5,
    },
  },
  {
    name: "Greek Yogurt Parfait",
    description:
      "A cup of Greek yogurt with a handful of granola and mixed berries.",
    calories: 350,
    protein_g: 25,
    carbs_g: 40,
    fat_g: 10,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "mediterranean",
    ingredient_tags: ["dairy", "oats", "berries"],
    recipe: {
      ingredients: [
        { name: "Greek yogurt", amount: "1", unit: "cup", category: "dairy" },
        { name: "Granola", amount: "1/3", unit: "cup", category: "grains" },
        { name: "Mixed berries", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Honey", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Spoon half the yogurt into a glass or bowl.",
        "Add a layer of granola and half the berries.",
        "Add the remaining yogurt on top.",
        "Finish with the rest of the berries, remaining granola, and a drizzle of honey.",
      ],
      prep_time_min: 3,
      cook_time_min: 0,
    },
  },
  {
    name: "Oatmeal with Banana & Peanut Butter",
    description:
      "A bowl of oatmeal topped with sliced banana and a spoonful of peanut butter.",
    calories: 450,
    protein_g: 15,
    carbs_g: 60,
    fat_g: 16,
    category: "breakfast",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["oats", "banana", "peanuts"],
    recipe: {
      ingredients: [
        { name: "Rolled oats", amount: "1/2", unit: "cup", category: "grains" },
        { name: "Water or milk", amount: "1", unit: "cup", category: "pantry" },
        { name: "Banana", amount: "1", unit: "medium", category: "produce" },
        { name: "Peanut butter", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Cinnamon", amount: "1/2", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Bring water or milk to a boil in a small pot.",
        "Stir in oats and reduce heat to medium-low. Cook for 4-5 minutes, stirring occasionally.",
        "Transfer to a bowl and top with sliced banana.",
        "Add a spoonful of peanut butter and sprinkle with cinnamon.",
      ],
      prep_time_min: 2,
      cook_time_min: 5,
    },
  },
  {
    name: "Protein Smoothie",
    description:
      "Blend a scoop of protein powder with a banana, handful of spinach, and almond milk.",
    calories: 300,
    protein_g: 30,
    carbs_g: 30,
    fat_g: 5,
    category: "breakfast",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["protein powder", "banana", "spinach", "almond milk"],
    recipe: {
      ingredients: [
        { name: "Protein powder", amount: "1", unit: "scoop", category: "pantry" },
        { name: "Banana", amount: "1", unit: "medium", category: "produce" },
        { name: "Spinach", amount: "1", unit: "handful", category: "produce" },
        { name: "Almond milk", amount: "1", unit: "cup", category: "dairy" },
        { name: "Ice cubes", amount: "4-5", unit: "cubes", category: "other" },
      ],
      steps: [
        "Add almond milk and spinach to a blender. Blend until spinach is broken down.",
        "Add banana, protein powder, and ice cubes.",
        "Blend on high for 30-45 seconds until smooth.",
        "Pour into a glass and serve immediately.",
      ],
      prep_time_min: 3,
      cook_time_min: 0,
    },
  },
  {
    name: "Avocado Toast with Eggs",
    description:
      "Mashed avocado on sourdough with two poached eggs and a sprinkle of salt.",
    calories: 480,
    protein_g: 22,
    carbs_g: 35,
    fat_g: 28,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "mediterranean",
    ingredient_tags: ["avocado", "wheat", "eggs"],
    recipe: {
      ingredients: [
        { name: "Sourdough bread", amount: "2", unit: "slices", category: "grains" },
        { name: "Avocado", amount: "1", unit: "medium", category: "produce" },
        { name: "Eggs", amount: "2", unit: "large", category: "protein" },
        { name: "Lemon juice", amount: "1", unit: "tsp", category: "produce" },
        { name: "Salt", amount: "1", unit: "pinch", category: "pantry" },
        { name: "Red pepper flakes", amount: "1", unit: "pinch", category: "pantry" },
      ],
      steps: [
        "Toast the sourdough slices until golden.",
        "Halve the avocado, scoop into a bowl, add lemon juice and salt, and mash with a fork.",
        "Bring a pot of water to a gentle simmer. Crack each egg into the water and poach for 3-4 minutes.",
        "Spread mashed avocado on each toast slice.",
        "Top each with a poached egg and sprinkle with red pepper flakes.",
      ],
      prep_time_min: 5,
      cook_time_min: 5,
    },
  },
  {
    name: "Bacon & Egg Wrap",
    description:
      "Two eggs and two strips of bacon in a whole wheat tortilla with cheese.",
    calories: 500,
    protein_g: 30,
    carbs_g: 30,
    fat_g: 28,
    category: "breakfast",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["eggs", "bacon", "wheat", "cheese", "dairy"],
    recipe: {
      ingredients: [
        { name: "Eggs", amount: "2", unit: "large", category: "protein" },
        { name: "Bacon", amount: "2", unit: "strips", category: "protein" },
        { name: "Whole wheat tortilla", amount: "1", unit: "large", category: "grains" },
        { name: "Cheddar cheese", amount: "1/4", unit: "cup shredded", category: "dairy" },
        { name: "Cooking spray", amount: "1", unit: "spray", category: "pantry" },
      ],
      steps: [
        "Cook bacon in a pan over medium heat until crispy. Set aside on paper towel.",
        "Scramble eggs in the same pan with a spray of cooking oil.",
        "Warm the tortilla in a dry pan or microwave for 10 seconds.",
        "Layer scrambled eggs, bacon, and cheese down the center of the tortilla.",
        "Fold in the sides and roll tightly. Cut in half to serve.",
      ],
      prep_time_min: 3,
      cook_time_min: 8,
    },
  },
  {
    name: "Keto Egg Cups",
    description:
      "Baked eggs in muffin tins with cheese, spinach, and diced ham.",
    calories: 350,
    protein_g: 28,
    carbs_g: 4,
    fat_g: 25,
    category: "breakfast",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["eggs", "cheese", "dairy", "spinach", "ham"],
    recipe: {
      ingredients: [
        { name: "Eggs", amount: "6", unit: "large", category: "protein" },
        { name: "Diced ham", amount: "1/2", unit: "cup", category: "protein" },
        { name: "Spinach", amount: "1", unit: "cup chopped", category: "produce" },
        { name: "Shredded cheese", amount: "1/2", unit: "cup", category: "dairy" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Preheat oven to 375°F (190°C). Grease a 6-cup muffin tin.",
        "Divide ham and spinach evenly among the muffin cups.",
        "Crack one egg into each cup. Season with salt and pepper.",
        "Top each with shredded cheese.",
        "Bake for 15-18 minutes until eggs are set. Let cool 2 minutes before removing.",
      ],
      prep_time_min: 5,
      cook_time_min: 18,
    },
  },
  {
    name: "Tofu Scramble",
    description:
      "Crumbled firm tofu sautéed with turmeric, onions, peppers, and nutritional yeast.",
    calories: 320,
    protein_g: 22,
    carbs_g: 15,
    fat_g: 18,
    category: "breakfast",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["tofu", "soy", "onion", "peppers", "nutritional yeast"],
    recipe: {
      ingredients: [
        { name: "Firm tofu", amount: "1/2", unit: "block", category: "protein" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Onion", amount: "1/4", unit: "diced", category: "produce" },
        { name: "Bell pepper", amount: "1/2", unit: "diced", category: "produce" },
        { name: "Turmeric", amount: "1/2", unit: "tsp", category: "pantry" },
        { name: "Nutritional yeast", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Press tofu to remove excess water, then crumble into small pieces.",
        "Heat olive oil in a pan over medium heat. Sauté onion and pepper for 3 minutes.",
        "Add crumbled tofu and turmeric. Cook for 5-7 minutes, stirring occasionally.",
        "Sprinkle with nutritional yeast, salt, and pepper. Stir to combine.",
        "Serve hot, optionally with toast or in a tortilla.",
      ],
      prep_time_min: 5,
      cook_time_min: 10,
    },
  },
  {
    name: "Smoked Salmon Bagel",
    description:
      "Half a bagel with cream cheese, smoked salmon, capers, and red onion.",
    calories: 400,
    protein_g: 25,
    carbs_g: 30,
    fat_g: 18,
    category: "breakfast",
    tags: ["no_preference", "pescatarian"],
    cuisine: "american",
    ingredient_tags: ["salmon", "fish", "wheat", "cream cheese", "dairy", "capers", "onion"],
    recipe: {
      ingredients: [
        { name: "Bagel", amount: "1", unit: "whole (use half)", category: "grains" },
        { name: "Cream cheese", amount: "2", unit: "tbsp", category: "dairy" },
        { name: "Smoked salmon", amount: "2", unit: "oz", category: "protein" },
        { name: "Capers", amount: "1", unit: "tsp", category: "pantry" },
        { name: "Red onion", amount: "2", unit: "thin slices", category: "produce" },
        { name: "Fresh dill", amount: "1", unit: "sprig", category: "produce" },
      ],
      steps: [
        "Slice the bagel in half and toast until golden.",
        "Spread cream cheese generously on the toasted half.",
        "Layer smoked salmon slices on top.",
        "Garnish with capers, red onion slices, and fresh dill.",
        "Serve the other bagel half on the side or save for later.",
      ],
      prep_time_min: 5,
      cook_time_min: 2,
    },
  },
  {
    name: "Overnight Oats",
    description:
      "Oats soaked overnight in milk with chia seeds, honey, and mixed nuts.",
    calories: 400,
    protein_g: 15,
    carbs_g: 55,
    fat_g: 14,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["oats", "dairy", "chia seeds", "nuts", "honey"],
    recipe: {
      ingredients: [
        { name: "Rolled oats", amount: "1/2", unit: "cup", category: "grains" },
        { name: "Milk", amount: "1/2", unit: "cup", category: "dairy" },
        { name: "Chia seeds", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Honey", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Mixed nuts", amount: "2", unit: "tbsp chopped", category: "pantry" },
      ],
      steps: [
        "Combine oats, milk, and chia seeds in a jar or container.",
        "Stir in honey and mix well.",
        "Cover and refrigerate overnight (at least 6 hours).",
        "In the morning, stir and top with chopped mixed nuts.",
        "Eat cold or microwave for 1-2 minutes if you prefer it warm.",
      ],
      prep_time_min: 5,
      cook_time_min: 0,
    },
  },
  {
    name: "Cottage Cheese Bowl",
    description:
      "A cup of cottage cheese topped with pineapple chunks and a drizzle of honey.",
    calories: 280,
    protein_g: 28,
    carbs_g: 25,
    fat_g: 6,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["dairy", "cottage cheese", "pineapple", "honey"],
    recipe: {
      ingredients: [
        { name: "Cottage cheese", amount: "1", unit: "cup", category: "dairy" },
        { name: "Pineapple chunks", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Honey", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Scoop cottage cheese into a bowl.",
        "Top with pineapple chunks.",
        "Drizzle honey over the top and serve.",
      ],
      prep_time_min: 2,
      cook_time_min: 0,
    },
  },
  {
    name: "Banana Pancakes",
    description:
      "Two-ingredient pancakes made with banana and eggs, topped with maple syrup.",
    calories: 350,
    protein_g: 15,
    carbs_g: 45,
    fat_g: 12,
    category: "breakfast",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["banana", "eggs", "maple syrup"],
    recipe: {
      ingredients: [
        { name: "Banana", amount: "1", unit: "large", category: "produce" },
        { name: "Eggs", amount: "2", unit: "large", category: "protein" },
        { name: "Maple syrup", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Cooking spray", amount: "1", unit: "spray", category: "pantry" },
      ],
      steps: [
        "Mash the banana in a bowl until smooth. Whisk in eggs until combined.",
        "Heat a non-stick pan over medium heat with cooking spray.",
        "Pour small circles of batter and cook 2 minutes per side until golden.",
        "Serve with a drizzle of maple syrup.",
      ],
      prep_time_min: 3,
      cook_time_min: 6,
    },
  },

  // LUNCH (14 options)
  {
    name: "Grilled Chicken & Rice",
    description:
      "A palm-sized grilled chicken breast with a cup of rice and steamed broccoli.",
    calories: 504,
    protein_g: 40,
    carbs_g: 50,
    fat_g: 16,
    category: "lunch",
    tags: ["no_preference"],
    cuisine: "american",
    ingredient_tags: ["chicken", "rice", "broccoli"],
    recipe: {
      ingredients: [
        { name: "Chicken breast", amount: "6", unit: "oz", category: "protein" },
        { name: "White rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Broccoli", amount: "1", unit: "cup", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
        { name: "Garlic powder", amount: "1/2", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Season chicken breast with salt, pepper, and garlic powder.",
        "Heat olive oil in a grill pan over medium-high heat. Cook chicken 5-6 minutes per side until cooked through.",
        "Steam broccoli for 3-4 minutes until tender-crisp.",
        "Cook rice according to package directions.",
        "Slice chicken and serve over rice with broccoli on the side.",
      ],
      prep_time_min: 5,
      cook_time_min: 15,
    },
  },
  {
    name: "Turkey Sandwich",
    description:
      "Sliced turkey on whole grain bread with lettuce, tomato, and mustard.",
    calories: 420,
    protein_g: 30,
    carbs_g: 40,
    fat_g: 14,
    category: "lunch",
    tags: ["no_preference"],
    cuisine: "american",
    ingredient_tags: ["turkey", "wheat", "lettuce", "tomato"],
    recipe: {
      ingredients: [
        { name: "Sliced turkey", amount: "4", unit: "oz", category: "protein" },
        { name: "Whole grain bread", amount: "2", unit: "slices", category: "grains" },
        { name: "Lettuce", amount: "2", unit: "leaves", category: "produce" },
        { name: "Tomato", amount: "2", unit: "slices", category: "produce" },
        { name: "Mustard", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Lay out two slices of whole grain bread.",
        "Spread mustard on one slice.",
        "Layer turkey, lettuce, and tomato slices.",
        "Close the sandwich, cut in half, and serve.",
      ],
      prep_time_min: 5,
      cook_time_min: 0,
    },
  },
  {
    name: "Tuna Salad Bowl",
    description:
      "A can of tuna mixed with Greek yogurt, celery, and served on a bed of greens.",
    calories: 380,
    protein_g: 35,
    carbs_g: 15,
    fat_g: 18,
    category: "lunch",
    tags: ["no_preference", "pescatarian", "keto"],
    cuisine: "mediterranean",
    ingredient_tags: ["tuna", "fish", "dairy", "celery", "greens"],
    recipe: {
      ingredients: [
        { name: "Canned tuna", amount: "1", unit: "can (5oz)", category: "protein" },
        { name: "Greek yogurt", amount: "2", unit: "tbsp", category: "dairy" },
        { name: "Celery", amount: "1", unit: "stalk diced", category: "produce" },
        { name: "Mixed greens", amount: "2", unit: "cups", category: "produce" },
        { name: "Lemon juice", amount: "1", unit: "tsp", category: "produce" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Drain the tuna and place in a bowl.",
        "Mix in Greek yogurt, diced celery, lemon juice, salt, and pepper.",
        "Arrange mixed greens on a plate or in a bowl.",
        "Spoon the tuna salad over the greens and serve.",
      ],
      prep_time_min: 5,
      cook_time_min: 0,
    },
  },
  {
    name: "Chicken Caesar Wrap",
    description:
      "Grilled chicken strips with romaine, parmesan, and Caesar dressing in a tortilla.",
    calories: 520,
    protein_g: 35,
    carbs_g: 38,
    fat_g: 22,
    category: "lunch",
    tags: ["no_preference"],
    cuisine: "american",
    ingredient_tags: ["chicken", "wheat", "dairy", "parmesan", "lettuce"],
    recipe: {
      ingredients: [
        { name: "Grilled chicken breast", amount: "4", unit: "oz sliced", category: "protein" },
        { name: "Romaine lettuce", amount: "2", unit: "cups chopped", category: "produce" },
        { name: "Parmesan cheese", amount: "2", unit: "tbsp shaved", category: "dairy" },
        { name: "Caesar dressing", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "Whole wheat tortilla", amount: "1", unit: "large", category: "grains" },
      ],
      steps: [
        "Slice grilled chicken into thin strips.",
        "Toss romaine, chicken, parmesan, and dressing in a bowl.",
        "Warm the tortilla in a dry pan for 10 seconds per side.",
        "Spoon the Caesar salad mixture down the center and wrap tightly.",
        "Cut in half and serve.",
      ],
      prep_time_min: 5,
      cook_time_min: 2,
    },
  },
  {
    name: "Beef Stir Fry",
    description:
      "Strips of beef stir-fried with mixed veggies and soy sauce, served over rice.",
    calories: 550,
    protein_g: 35,
    carbs_g: 55,
    fat_g: 18,
    category: "lunch",
    tags: ["no_preference"],
    cuisine: "asian",
    ingredient_tags: ["beef", "soy", "rice", "vegetables"],
    recipe: {
      ingredients: [
        { name: "Beef sirloin", amount: "5", unit: "oz sliced thin", category: "protein" },
        { name: "Mixed vegetables", amount: "1.5", unit: "cups", category: "produce" },
        { name: "Soy sauce", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "White rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Sesame oil", amount: "1", unit: "tsp", category: "pantry" },
        { name: "Garlic", amount: "2", unit: "cloves minced", category: "produce" },
      ],
      steps: [
        "Cook rice according to package directions.",
        "Heat sesame oil in a wok or large pan over high heat.",
        "Stir-fry beef strips for 2-3 minutes until browned. Remove and set aside.",
        "Add garlic and mixed vegetables. Stir-fry for 3-4 minutes.",
        "Return beef, add soy sauce, toss to combine, and serve over rice.",
      ],
      prep_time_min: 10,
      cook_time_min: 10,
    },
  },
  {
    name: "Lentil Soup & Bread",
    description:
      "A hearty bowl of lentil soup with a slice of crusty bread on the side.",
    calories: 400,
    protein_g: 22,
    carbs_g: 55,
    fat_g: 8,
    category: "lunch",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "mediterranean",
    ingredient_tags: ["lentils", "wheat", "onion", "carrot", "celery"],
    recipe: {
      ingredients: [
        { name: "Green or brown lentils", amount: "1", unit: "cup dry", category: "pantry" },
        { name: "Onion", amount: "1", unit: "small diced", category: "produce" },
        { name: "Carrot", amount: "1", unit: "diced", category: "produce" },
        { name: "Celery", amount: "1", unit: "stalk diced", category: "produce" },
        { name: "Crusty bread", amount: "1", unit: "slice", category: "grains" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Vegetable broth", amount: "3", unit: "cups", category: "pantry" },
      ],
      steps: [
        "Heat olive oil in a pot. Sauté onion, carrot, and celery for 5 minutes.",
        "Add lentils and vegetable broth. Bring to a boil.",
        "Reduce heat and simmer for 25-30 minutes until lentils are tender.",
        "Season with salt and pepper. Serve with crusty bread on the side.",
      ],
      prep_time_min: 5,
      cook_time_min: 30,
    },
  },
  {
    name: "Salmon Poke Bowl",
    description:
      "Cubed raw salmon over sushi rice with avocado, edamame, and soy sauce.",
    calories: 520,
    protein_g: 32,
    carbs_g: 50,
    fat_g: 20,
    category: "lunch",
    tags: ["no_preference", "pescatarian"],
    cuisine: "asian",
    ingredient_tags: ["salmon", "fish", "rice", "avocado", "soy", "edamame"],
    recipe: {
      ingredients: [
        { name: "Sushi-grade salmon", amount: "5", unit: "oz cubed", category: "protein" },
        { name: "Sushi rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Avocado", amount: "1/2", unit: "sliced", category: "produce" },
        { name: "Edamame", amount: "1/4", unit: "cup shelled", category: "produce" },
        { name: "Soy sauce", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Sesame seeds", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Cook sushi rice and let it cool slightly.",
        "Cube the salmon into bite-sized pieces.",
        "Place rice in a bowl. Arrange salmon, avocado, and edamame on top.",
        "Drizzle with soy sauce and sprinkle sesame seeds.",
      ],
      prep_time_min: 10,
      cook_time_min: 0,
    },
  },
  {
    name: "Black Bean Burrito Bowl",
    description:
      "Black beans, rice, corn, salsa, avocado, and a dollop of sour cream.",
    calories: 550,
    protein_g: 20,
    carbs_g: 70,
    fat_g: 18,
    category: "lunch",
    tags: ["no_preference", "vegetarian"],
    cuisine: "mexican",
    ingredient_tags: ["beans", "rice", "corn", "avocado", "dairy"],
    recipe: {
      ingredients: [
        { name: "Black beans", amount: "1/2", unit: "can drained", category: "pantry" },
        { name: "White rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Corn", amount: "1/4", unit: "cup", category: "produce" },
        { name: "Avocado", amount: "1/2", unit: "sliced", category: "produce" },
        { name: "Salsa", amount: "3", unit: "tbsp", category: "pantry" },
        { name: "Sour cream", amount: "1", unit: "tbsp", category: "dairy" },
      ],
      steps: [
        "Cook rice according to package directions.",
        "Heat black beans and corn in a small pan.",
        "Assemble bowl: rice on the bottom, beans and corn on top.",
        "Add sliced avocado, salsa, and a dollop of sour cream.",
      ],
      prep_time_min: 5,
      cook_time_min: 10,
    },
  },
  {
    name: "Grilled Chicken Salad",
    description:
      "Mixed greens with grilled chicken, cherry tomatoes, cucumber, and vinaigrette.",
    calories: 400,
    protein_g: 35,
    carbs_g: 15,
    fat_g: 22,
    category: "lunch",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["chicken", "greens", "tomato", "cucumber"],
    recipe: {
      ingredients: [
        { name: "Chicken breast", amount: "4", unit: "oz grilled", category: "protein" },
        { name: "Mixed greens", amount: "3", unit: "cups", category: "produce" },
        { name: "Cherry tomatoes", amount: "1/2", unit: "cup halved", category: "produce" },
        { name: "Cucumber", amount: "1/2", unit: "sliced", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Balsamic vinegar", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Grill or pan-sear chicken breast until cooked through. Let rest and slice.",
        "Toss mixed greens, tomatoes, and cucumber in a large bowl.",
        "Whisk olive oil and balsamic vinegar together for dressing.",
        "Top salad with sliced chicken and drizzle with dressing.",
      ],
      prep_time_min: 5,
      cook_time_min: 10,
    },
  },
  {
    name: "Veggie Stir Fry with Tofu",
    description:
      "Crispy tofu with broccoli, bell peppers, and snap peas in teriyaki sauce over rice.",
    calories: 480,
    protein_g: 22,
    carbs_g: 55,
    fat_g: 16,
    category: "lunch",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "asian",
    ingredient_tags: ["tofu", "soy", "broccoli", "peppers", "rice"],
    recipe: {
      ingredients: [
        { name: "Firm tofu", amount: "1/2", unit: "block cubed", category: "protein" },
        { name: "Broccoli", amount: "1", unit: "cup florets", category: "produce" },
        { name: "Bell pepper", amount: "1", unit: "sliced", category: "produce" },
        { name: "Snap peas", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Teriyaki sauce", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "White rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Sesame oil", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Press tofu and cut into cubes. Pan-fry in sesame oil until golden on all sides.",
        "Remove tofu. Add broccoli, pepper, and snap peas to the pan. Stir-fry 3-4 minutes.",
        "Return tofu to pan, add teriyaki sauce, and toss to coat.",
        "Serve over cooked rice.",
      ],
      prep_time_min: 10,
      cook_time_min: 12,
    },
  },
  {
    name: "Shrimp Tacos",
    description:
      "Grilled shrimp in corn tortillas with cabbage slaw, lime, and chipotle mayo.",
    calories: 450,
    protein_g: 30,
    carbs_g: 40,
    fat_g: 18,
    category: "lunch",
    tags: ["no_preference", "pescatarian"],
    cuisine: "mexican",
    ingredient_tags: ["shrimp", "shellfish", "corn", "cabbage", "lime"],
    recipe: {
      ingredients: [
        { name: "Shrimp", amount: "6", unit: "oz peeled", category: "protein" },
        { name: "Corn tortillas", amount: "3", unit: "small", category: "grains" },
        { name: "Cabbage", amount: "1", unit: "cup shredded", category: "produce" },
        { name: "Lime", amount: "1", unit: "whole", category: "produce" },
        { name: "Chipotle mayo", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Olive oil", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Season shrimp with salt and a squeeze of lime. Sauté in olive oil over high heat for 2 minutes per side.",
        "Warm corn tortillas in a dry pan.",
        "Toss shredded cabbage with lime juice for a quick slaw.",
        "Assemble tacos: tortilla, slaw, shrimp, and a drizzle of chipotle mayo.",
      ],
      prep_time_min: 10,
      cook_time_min: 5,
    },
  },
  {
    name: "Mediterranean Plate",
    description:
      "Hummus, falafel, tabbouleh, and pita bread with a side of mixed olives.",
    calories: 520,
    protein_g: 18,
    carbs_g: 55,
    fat_g: 24,
    category: "lunch",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "mediterranean",
    ingredient_tags: ["chickpeas", "wheat", "parsley", "olives"],
    recipe: {
      ingredients: [
        { name: "Hummus", amount: "1/4", unit: "cup", category: "pantry" },
        { name: "Falafel (frozen or premade)", amount: "4", unit: "pieces", category: "protein" },
        { name: "Tabbouleh", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Pita bread", amount: "1", unit: "round", category: "grains" },
        { name: "Mixed olives", amount: "2", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Heat falafel in the oven or air fryer according to package directions.",
        "Warm pita bread in a dry pan or microwave.",
        "Arrange hummus, falafel, tabbouleh, and olives on a plate.",
        "Tear pita and dip or stuff with the toppings.",
      ],
      prep_time_min: 5,
      cook_time_min: 10,
    },
  },
  {
    name: "Chicken Quesadilla",
    description:
      "Shredded chicken and melted cheese in a crispy tortilla with salsa on the side.",
    calories: 500,
    protein_g: 32,
    carbs_g: 35,
    fat_g: 24,
    category: "lunch",
    tags: ["no_preference"],
    cuisine: "mexican",
    ingredient_tags: ["chicken", "wheat", "cheese", "dairy"],
    recipe: {
      ingredients: [
        { name: "Shredded chicken", amount: "4", unit: "oz", category: "protein" },
        { name: "Flour tortilla", amount: "1", unit: "large", category: "grains" },
        { name: "Shredded cheese", amount: "1/3", unit: "cup", category: "dairy" },
        { name: "Salsa", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "Cooking spray", amount: "1", unit: "spray", category: "pantry" },
      ],
      steps: [
        "Place tortilla in a dry pan over medium heat.",
        "Spread cheese and chicken over one half of the tortilla.",
        "Fold tortilla in half and press down gently.",
        "Cook 2-3 minutes per side until golden and cheese is melted.",
        "Cut into wedges and serve with salsa.",
      ],
      prep_time_min: 3,
      cook_time_min: 6,
    },
  },
  {
    name: "Keto Burger Bowl",
    description:
      "Beef patty crumbled over lettuce with cheese, pickles, tomato, and special sauce.",
    calories: 480,
    protein_g: 35,
    carbs_g: 8,
    fat_g: 34,
    category: "lunch",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["beef", "cheese", "dairy", "lettuce", "tomato", "pickles"],
    recipe: {
      ingredients: [
        { name: "Ground beef", amount: "5", unit: "oz", category: "protein" },
        { name: "Romaine lettuce", amount: "2", unit: "cups chopped", category: "produce" },
        { name: "Cheddar cheese", amount: "1", unit: "slice", category: "dairy" },
        { name: "Dill pickles", amount: "3", unit: "slices", category: "pantry" },
        { name: "Tomato", amount: "2", unit: "slices", category: "produce" },
        { name: "Ketchup and mustard", amount: "1", unit: "tbsp each", category: "pantry" },
      ],
      steps: [
        "Form ground beef into a patty. Season with salt and pepper.",
        "Cook patty in a pan over medium-high heat, 4 minutes per side.",
        "Crumble the cooked patty over a bed of chopped lettuce.",
        "Top with cheese, pickles, tomato, ketchup, and mustard.",
      ],
      prep_time_min: 5,
      cook_time_min: 8,
    },
  },

  // DINNER (14 options)
  {
    name: "Baked Salmon with Sweet Potato",
    description:
      "A fillet of salmon baked with lemon, served with roasted sweet potato and green beans.",
    calories: 546,
    protein_g: 38,
    carbs_g: 40,
    fat_g: 26,
    category: "dinner",
    tags: ["no_preference", "pescatarian"],
    cuisine: "mediterranean",
    ingredient_tags: ["salmon", "fish", "sweet potato", "green beans", "lemon"],
    recipe: {
      ingredients: [
        { name: "Salmon fillet", amount: "6", unit: "oz", category: "protein" },
        { name: "Sweet potato", amount: "1", unit: "medium", category: "produce" },
        { name: "Green beans", amount: "1", unit: "cup", category: "produce" },
        { name: "Lemon", amount: "1/2", unit: "sliced", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Preheat oven to 400°F (200°C). Cube sweet potato, toss with olive oil, and roast for 25 minutes.",
        "Season salmon with salt, pepper, and lemon slices.",
        "Place salmon on a baking sheet and bake for 12-15 minutes.",
        "Steam green beans for 4 minutes until tender-crisp.",
        "Serve salmon with roasted sweet potato and green beans.",
      ],
      prep_time_min: 10,
      cook_time_min: 25,
    },
  },
  {
    name: "Chicken Breast with Quinoa",
    description:
      "Seasoned chicken breast with a cup of quinoa and roasted Mediterranean vegetables.",
    calories: 519,
    protein_g: 42,
    carbs_g: 45,
    fat_g: 19,
    category: "dinner",
    tags: ["no_preference"],
    cuisine: "mediterranean",
    ingredient_tags: ["chicken", "quinoa", "vegetables", "olive oil"],
    recipe: {
      ingredients: [
        { name: "Chicken breast", amount: "6", unit: "oz", category: "protein" },
        { name: "Quinoa", amount: "1/2", unit: "cup dry", category: "grains" },
        { name: "Zucchini", amount: "1", unit: "medium diced", category: "produce" },
        { name: "Bell pepper", amount: "1", unit: "diced", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Italian seasoning", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Cook quinoa according to package directions.",
        "Season chicken with Italian seasoning, salt, and pepper.",
        "Grill or pan-sear chicken for 6 minutes per side. Let rest and slice.",
        "Toss diced vegetables with olive oil and roast at 400°F for 15 minutes.",
        "Serve sliced chicken over quinoa with roasted vegetables.",
      ],
      prep_time_min: 10,
      cook_time_min: 20,
    },
  },
  {
    name: "Pasta with Meat Sauce",
    description:
      "Whole wheat pasta with ground beef tomato sauce topped with parmesan.",
    calories: 604,
    protein_g: 32,
    carbs_g: 65,
    fat_g: 24,
    category: "dinner",
    tags: ["no_preference"],
    cuisine: "italian",
    ingredient_tags: ["wheat", "beef", "tomato", "parmesan", "dairy"],
    recipe: {
      ingredients: [
        { name: "Whole wheat pasta", amount: "2", unit: "oz dry", category: "grains" },
        { name: "Ground beef", amount: "4", unit: "oz", category: "protein" },
        { name: "Crushed tomatoes", amount: "1/2", unit: "cup", category: "pantry" },
        { name: "Garlic", amount: "2", unit: "cloves minced", category: "produce" },
        { name: "Parmesan cheese", amount: "2", unit: "tbsp grated", category: "dairy" },
        { name: "Olive oil", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Cook pasta according to package directions. Drain and set aside.",
        "Brown ground beef in a pan over medium heat. Drain excess fat.",
        "Add garlic and cook 30 seconds. Add crushed tomatoes and simmer 10 minutes.",
        "Toss pasta with the meat sauce.",
        "Serve topped with grated parmesan.",
      ],
      prep_time_min: 5,
      cook_time_min: 20,
    },
  },
  {
    name: "Steak with Roasted Vegetables",
    description:
      "A 6oz sirloin steak with roasted potatoes, carrots, and asparagus.",
    calories: 581,
    protein_g: 45,
    carbs_g: 35,
    fat_g: 29,
    category: "dinner",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["beef", "potato", "carrot", "asparagus"],
    recipe: {
      ingredients: [
        { name: "Sirloin steak", amount: "6", unit: "oz", category: "protein" },
        { name: "Baby potatoes", amount: "1", unit: "cup halved", category: "produce" },
        { name: "Carrots", amount: "2", unit: "medium chopped", category: "produce" },
        { name: "Asparagus", amount: "6", unit: "spears", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Preheat oven to 425°F (220°C). Toss potatoes and carrots with olive oil, salt, and pepper. Roast 20 minutes.",
        "Add asparagus to the pan and roast 8 more minutes.",
        "Season steak with salt and pepper. Sear in a hot pan 4 minutes per side for medium.",
        "Let steak rest 5 minutes, then slice against the grain.",
        "Serve steak with roasted vegetables.",
      ],
      prep_time_min: 10,
      cook_time_min: 28,
    },
  },
  {
    name: "Vegetable Curry with Rice",
    description: "Mixed vegetable coconut curry served over basmati rice.",
    calories: 500,
    protein_g: 14,
    carbs_g: 65,
    fat_g: 20,
    category: "dinner",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "mediterranean",
    ingredient_tags: ["coconut", "rice", "vegetables", "curry spices"],
    recipe: {
      ingredients: [
        { name: "Mixed vegetables", amount: "2", unit: "cups chopped", category: "produce" },
        { name: "Coconut milk", amount: "1", unit: "can (14oz)", category: "pantry" },
        { name: "Curry paste", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "Basmati rice", amount: "1", unit: "cup cooked", category: "grains" },
        { name: "Onion", amount: "1", unit: "small diced", category: "produce" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Cook rice according to package directions.",
        "Heat olive oil in a pot. Sauté onion for 3 minutes.",
        "Add curry paste and stir for 1 minute until fragrant.",
        "Add mixed vegetables and coconut milk. Simmer for 15 minutes.",
        "Serve curry over rice.",
      ],
      prep_time_min: 10,
      cook_time_min: 20,
    },
  },
  {
    name: "Grilled Fish Tacos",
    description:
      "White fish grilled and served in corn tortillas with avocado crema and slaw.",
    calories: 480,
    protein_g: 32,
    carbs_g: 40,
    fat_g: 20,
    category: "dinner",
    tags: ["no_preference", "pescatarian"],
    cuisine: "mexican",
    ingredient_tags: ["fish", "corn", "avocado", "cabbage", "lime"],
    recipe: {
      ingredients: [
        { name: "White fish fillet", amount: "6", unit: "oz", category: "protein" },
        { name: "Corn tortillas", amount: "3", unit: "small", category: "grains" },
        { name: "Avocado", amount: "1/2", unit: "mashed", category: "produce" },
        { name: "Cabbage", amount: "1", unit: "cup shredded", category: "produce" },
        { name: "Lime", amount: "1", unit: "whole", category: "produce" },
        { name: "Sour cream", amount: "1", unit: "tbsp", category: "dairy" },
      ],
      steps: [
        "Season fish with salt, pepper, and lime juice. Grill or pan-sear 3-4 minutes per side.",
        "Warm tortillas in a dry pan.",
        "Mix sour cream with lime juice for a crema.",
        "Flake fish and divide among tortillas. Top with cabbage slaw and avocado.",
        "Drizzle with lime crema and serve.",
      ],
      prep_time_min: 10,
      cook_time_min: 8,
    },
  },
  {
    name: "Chicken Thigh with Mashed Potatoes",
    description:
      "Crispy skin chicken thighs with creamy mashed potatoes and steamed peas.",
    calories: 580,
    protein_g: 35,
    carbs_g: 45,
    fat_g: 28,
    category: "dinner",
    tags: ["no_preference"],
    cuisine: "american",
    ingredient_tags: ["chicken", "potato", "dairy", "butter", "peas"],
    recipe: {
      ingredients: [
        { name: "Chicken thighs", amount: "2", unit: "bone-in", category: "protein" },
        { name: "Potatoes", amount: "2", unit: "medium peeled", category: "produce" },
        { name: "Butter", amount: "2", unit: "tbsp", category: "dairy" },
        { name: "Milk", amount: "1/4", unit: "cup", category: "dairy" },
        { name: "Frozen peas", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Preheat oven to 425°F (220°C). Season chicken thighs and roast skin-side up for 35 minutes.",
        "Boil potatoes until fork-tender, about 15 minutes. Drain.",
        "Mash potatoes with butter and milk until creamy. Season with salt and pepper.",
        "Steam peas for 2 minutes.",
        "Serve chicken thighs with mashed potatoes and peas.",
      ],
      prep_time_min: 10,
      cook_time_min: 35,
    },
  },
  {
    name: "Tofu Pad Thai",
    description:
      "Rice noodles stir-fried with tofu, bean sprouts, peanuts, and pad thai sauce.",
    calories: 500,
    protein_g: 20,
    carbs_g: 60,
    fat_g: 18,
    category: "dinner",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "asian",
    ingredient_tags: ["tofu", "soy", "rice noodles", "peanuts", "bean sprouts"],
    recipe: {
      ingredients: [
        { name: "Rice noodles", amount: "4", unit: "oz", category: "grains" },
        { name: "Firm tofu", amount: "1/2", unit: "block cubed", category: "protein" },
        { name: "Bean sprouts", amount: "1/2", unit: "cup", category: "produce" },
        { name: "Peanuts", amount: "2", unit: "tbsp crushed", category: "pantry" },
        { name: "Pad Thai sauce", amount: "3", unit: "tbsp", category: "pantry" },
        { name: "Lime", amount: "1/2", unit: "wedge", category: "produce" },
        { name: "Vegetable oil", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Soak rice noodles in hot water for 8 minutes. Drain.",
        "Pan-fry tofu cubes in oil until golden. Set aside.",
        "In the same pan, add noodles, pad Thai sauce, and toss for 2 minutes.",
        "Add tofu and bean sprouts. Toss to combine.",
        "Serve topped with crushed peanuts and a lime wedge.",
      ],
      prep_time_min: 10,
      cook_time_min: 12,
    },
  },
  {
    name: "Stuffed Bell Peppers",
    description:
      "Bell peppers stuffed with ground turkey, rice, tomato sauce, and melted cheese.",
    calories: 450,
    protein_g: 30,
    carbs_g: 40,
    fat_g: 16,
    category: "dinner",
    tags: ["no_preference"],
    cuisine: "american",
    ingredient_tags: ["turkey", "peppers", "rice", "tomato", "cheese", "dairy"],
    recipe: {
      ingredients: [
        { name: "Bell peppers", amount: "2", unit: "large", category: "produce" },
        { name: "Ground turkey", amount: "4", unit: "oz", category: "protein" },
        { name: "Cooked rice", amount: "1/2", unit: "cup", category: "grains" },
        { name: "Tomato sauce", amount: "1/4", unit: "cup", category: "pantry" },
        { name: "Shredded cheese", amount: "1/4", unit: "cup", category: "dairy" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Preheat oven to 375°F (190°C). Cut tops off peppers and remove seeds.",
        "Brown ground turkey in a pan. Mix with cooked rice and tomato sauce.",
        "Stuff peppers with the mixture and place in a baking dish.",
        "Bake for 25 minutes. Top with cheese and bake 5 more minutes.",
        "Let cool slightly before serving.",
      ],
      prep_time_min: 10,
      cook_time_min: 30,
    },
  },
  {
    name: "Pesto Pasta with Chicken",
    description:
      "Penne pasta tossed in basil pesto with grilled chicken and cherry tomatoes.",
    calories: 580,
    protein_g: 35,
    carbs_g: 55,
    fat_g: 24,
    category: "dinner",
    tags: ["no_preference"],
    cuisine: "italian",
    ingredient_tags: ["wheat", "chicken", "basil", "pine nuts", "parmesan", "dairy"],
    recipe: {
      ingredients: [
        { name: "Penne pasta", amount: "2", unit: "oz dry", category: "grains" },
        { name: "Chicken breast", amount: "4", unit: "oz grilled", category: "protein" },
        { name: "Basil pesto", amount: "2", unit: "tbsp", category: "pantry" },
        { name: "Cherry tomatoes", amount: "1/2", unit: "cup halved", category: "produce" },
        { name: "Parmesan cheese", amount: "1", unit: "tbsp grated", category: "dairy" },
      ],
      steps: [
        "Cook penne according to package directions. Drain, reserving 2 tbsp pasta water.",
        "Slice grilled chicken into strips.",
        "Toss pasta with pesto and a splash of pasta water.",
        "Add cherry tomatoes and chicken. Mix gently.",
        "Serve topped with grated parmesan.",
      ],
      prep_time_min: 5,
      cook_time_min: 12,
    },
  },
  {
    name: "Bean & Cheese Enchiladas",
    description:
      "Black bean and cheese enchiladas with red sauce, sour cream, and a side salad.",
    calories: 520,
    protein_g: 22,
    carbs_g: 55,
    fat_g: 22,
    category: "dinner",
    tags: ["no_preference", "vegetarian"],
    cuisine: "mexican",
    ingredient_tags: ["beans", "cheese", "dairy", "corn", "tomato"],
    recipe: {
      ingredients: [
        { name: "Black beans", amount: "1/2", unit: "can drained", category: "pantry" },
        { name: "Shredded cheese", amount: "1/2", unit: "cup", category: "dairy" },
        { name: "Corn tortillas", amount: "4", unit: "small", category: "grains" },
        { name: "Red enchilada sauce", amount: "1", unit: "cup", category: "pantry" },
        { name: "Sour cream", amount: "2", unit: "tbsp", category: "dairy" },
        { name: "Mixed greens", amount: "1", unit: "cup", category: "produce" },
      ],
      steps: [
        "Preheat oven to 375°F (190°C). Spread a thin layer of enchilada sauce in a baking dish.",
        "Fill each tortilla with beans and half the cheese. Roll and place seam-side down.",
        "Pour remaining enchilada sauce over the top. Sprinkle with remaining cheese.",
        "Bake for 20 minutes until bubbly.",
        "Serve with sour cream and a side salad.",
      ],
      prep_time_min: 10,
      cook_time_min: 20,
    },
  },
  {
    name: "Keto Chicken Alfredo",
    description:
      "Grilled chicken in creamy alfredo sauce served over zucchini noodles.",
    calories: 480,
    protein_g: 38,
    carbs_g: 10,
    fat_g: 32,
    category: "dinner",
    tags: ["no_preference", "keto"],
    cuisine: "italian",
    ingredient_tags: ["chicken", "dairy", "cream", "parmesan", "zucchini"],
    recipe: {
      ingredients: [
        { name: "Chicken breast", amount: "6", unit: "oz", category: "protein" },
        { name: "Zucchini", amount: "2", unit: "medium spiralized", category: "produce" },
        { name: "Heavy cream", amount: "1/4", unit: "cup", category: "dairy" },
        { name: "Parmesan cheese", amount: "2", unit: "tbsp grated", category: "dairy" },
        { name: "Garlic", amount: "2", unit: "cloves minced", category: "produce" },
        { name: "Butter", amount: "1", unit: "tbsp", category: "dairy" },
      ],
      steps: [
        "Season and grill chicken breast. Let rest and slice.",
        "Melt butter in a pan. Sauté garlic for 30 seconds.",
        "Add heavy cream and parmesan. Stir until sauce thickens.",
        "Add zucchini noodles and toss for 2 minutes until just tender.",
        "Top with sliced chicken and serve.",
      ],
      prep_time_min: 10,
      cook_time_min: 15,
    },
  },
  {
    name: "Shrimp & Grits",
    description:
      "Sautéed shrimp in garlic butter served over creamy stone-ground grits.",
    calories: 520,
    protein_g: 30,
    carbs_g: 45,
    fat_g: 22,
    category: "dinner",
    tags: ["no_preference", "pescatarian"],
    cuisine: "american",
    ingredient_tags: ["shrimp", "shellfish", "corn", "butter", "dairy"],
    recipe: {
      ingredients: [
        { name: "Shrimp", amount: "6", unit: "oz peeled", category: "protein" },
        { name: "Stone-ground grits", amount: "1/2", unit: "cup dry", category: "grains" },
        { name: "Butter", amount: "2", unit: "tbsp", category: "dairy" },
        { name: "Garlic", amount: "2", unit: "cloves minced", category: "produce" },
        { name: "Milk", amount: "1/4", unit: "cup", category: "dairy" },
        { name: "Salt and pepper", amount: "1", unit: "pinch each", category: "pantry" },
      ],
      steps: [
        "Cook grits according to package directions. Stir in 1 tbsp butter and milk. Keep warm.",
        "Season shrimp with salt and pepper.",
        "Melt remaining butter in a pan. Sauté garlic for 30 seconds.",
        "Add shrimp and cook 2 minutes per side until pink.",
        "Serve shrimp over creamy grits.",
      ],
      prep_time_min: 5,
      cook_time_min: 20,
    },
  },
  {
    name: "Chickpea & Spinach Stew",
    description:
      "A warming stew of chickpeas, spinach, tomatoes, and spices served with bread.",
    calories: 420,
    protein_g: 18,
    carbs_g: 55,
    fat_g: 12,
    category: "dinner",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "mediterranean",
    ingredient_tags: ["chickpeas", "spinach", "tomato", "wheat"],
    recipe: {
      ingredients: [
        { name: "Chickpeas", amount: "1", unit: "can drained", category: "pantry" },
        { name: "Spinach", amount: "2", unit: "cups", category: "produce" },
        { name: "Diced tomatoes", amount: "1", unit: "can (14oz)", category: "pantry" },
        { name: "Onion", amount: "1", unit: "small diced", category: "produce" },
        { name: "Cumin", amount: "1", unit: "tsp", category: "pantry" },
        { name: "Crusty bread", amount: "1", unit: "slice", category: "grains" },
        { name: "Olive oil", amount: "1", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Heat olive oil in a pot. Sauté onion for 3 minutes.",
        "Add cumin and stir for 30 seconds.",
        "Add chickpeas and diced tomatoes. Simmer for 15 minutes.",
        "Stir in spinach and cook until wilted, about 2 minutes.",
        "Serve with crusty bread on the side.",
      ],
      prep_time_min: 5,
      cook_time_min: 20,
    },
  },

  // SNACKS (10 options)
  {
    name: "Protein Bar",
    description:
      "A protein bar — check the label for one with at least 20g protein.",
    calories: 250,
    protein_g: 20,
    carbs_g: 25,
    fat_g: 8,
    category: "snack",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["protein powder", "oats", "chocolate"],
    recipe: {
      ingredients: [
        { name: "Protein bar", amount: "1", unit: "bar", category: "pantry" },
      ],
      steps: [
        "Unwrap the protein bar.",
        "Check the label: aim for at least 20g protein and under 250 calories.",
        "Enjoy as-is or pair with water or coffee.",
      ],
      prep_time_min: 0,
      cook_time_min: 0,
    },
  },
  {
    name: "Apple & Peanut Butter",
    description: "A sliced apple with two tablespoons of peanut butter.",
    calories: 280,
    protein_g: 8,
    carbs_g: 30,
    fat_g: 16,
    category: "snack",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["apple", "peanuts"],
    recipe: {
      ingredients: [
        { name: "Apple", amount: "1", unit: "medium", category: "produce" },
        { name: "Peanut butter", amount: "2", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Wash and slice the apple into wedges.",
        "Serve with peanut butter for dipping.",
      ],
      prep_time_min: 2,
      cook_time_min: 0,
    },
  },
  {
    name: "Greek Yogurt & Honey",
    description: "A cup of plain Greek yogurt with a drizzle of honey.",
    calories: 180,
    protein_g: 18,
    carbs_g: 20,
    fat_g: 3,
    category: "snack",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["dairy", "honey"],
    recipe: {
      ingredients: [
        { name: "Greek yogurt", amount: "1", unit: "cup", category: "dairy" },
        { name: "Honey", amount: "1", unit: "tsp", category: "pantry" },
      ],
      steps: [
        "Scoop yogurt into a bowl.",
        "Drizzle with honey and serve.",
      ],
      prep_time_min: 1,
      cook_time_min: 0,
    },
  },
  {
    name: "Trail Mix",
    description: "A handful of mixed nuts, seeds, and dried fruit.",
    calories: 300,
    protein_g: 10,
    carbs_g: 25,
    fat_g: 20,
    category: "snack",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["nuts", "seeds", "dried fruit"],
    recipe: {
      ingredients: [
        { name: "Mixed nuts", amount: "1/4", unit: "cup", category: "pantry" },
        { name: "Sunflower seeds", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Dried cranberries", amount: "2", unit: "tbsp", category: "pantry" },
      ],
      steps: [
        "Combine nuts, seeds, and dried fruit in a small container.",
        "Portion into a snack bag for on-the-go or eat from a bowl.",
      ],
      prep_time_min: 1,
      cook_time_min: 0,
    },
  },
  {
    name: "String Cheese & Crackers",
    description:
      "Two sticks of string cheese with a handful of whole wheat crackers.",
    calories: 220,
    protein_g: 14,
    carbs_g: 18,
    fat_g: 10,
    category: "snack",
    tags: ["no_preference", "vegetarian"],
    cuisine: "american",
    ingredient_tags: ["dairy", "cheese", "wheat"],
    recipe: {
      ingredients: [
        { name: "String cheese", amount: "2", unit: "sticks", category: "dairy" },
        { name: "Whole wheat crackers", amount: "8", unit: "crackers", category: "grains" },
      ],
      steps: [
        "Unwrap string cheese sticks.",
        "Arrange on a plate with crackers and enjoy.",
      ],
      prep_time_min: 1,
      cook_time_min: 0,
    },
  },
  {
    name: "Hard Boiled Eggs",
    description: "Two hard boiled eggs with a pinch of salt and pepper.",
    calories: 160,
    protein_g: 12,
    carbs_g: 2,
    fat_g: 10,
    category: "snack",
    tags: ["no_preference", "vegetarian", "keto"],
    cuisine: "american",
    ingredient_tags: ["eggs"],
    recipe: {
      ingredients: [
        { name: "Eggs", amount: "2", unit: "large", category: "protein" },
        { name: "Salt", amount: "1", unit: "pinch", category: "pantry" },
        { name: "Black pepper", amount: "1", unit: "pinch", category: "pantry" },
      ],
      steps: [
        "Place eggs in a pot and cover with cold water by 1 inch.",
        "Bring to a boil, then cover and remove from heat. Let sit 10 minutes.",
        "Transfer eggs to an ice bath for 5 minutes.",
        "Peel, sprinkle with salt and pepper, and serve.",
      ],
      prep_time_min: 2,
      cook_time_min: 15,
    },
  },
  {
    name: "Hummus & Veggies",
    description:
      "A quarter cup of hummus with carrot sticks, celery, and bell pepper strips.",
    calories: 200,
    protein_g: 8,
    carbs_g: 22,
    fat_g: 10,
    category: "snack",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["chickpeas", "carrot", "celery", "peppers"],
    recipe: {
      ingredients: [
        { name: "Hummus", amount: "1/4", unit: "cup", category: "pantry" },
        { name: "Carrot sticks", amount: "1", unit: "medium", category: "produce" },
        { name: "Celery sticks", amount: "2", unit: "stalks", category: "produce" },
        { name: "Bell pepper strips", amount: "1/2", unit: "pepper", category: "produce" },
      ],
      steps: [
        "Cut carrots, celery, and bell pepper into sticks.",
        "Scoop hummus into a small bowl.",
        "Arrange veggies on a plate and dip away.",
      ],
      prep_time_min: 5,
      cook_time_min: 0,
    },
  },
  {
    name: "Beef Jerky",
    description: "A serving of beef jerky — about 1 oz.",
    calories: 120,
    protein_g: 15,
    carbs_g: 5,
    fat_g: 4,
    category: "snack",
    tags: ["no_preference", "keto"],
    cuisine: "american",
    ingredient_tags: ["beef"],
    recipe: {
      ingredients: [
        { name: "Beef jerky", amount: "1", unit: "oz", category: "protein" },
      ],
      steps: [
        "Open the package and portion out 1 oz (about a handful).",
        "Enjoy as a high-protein, portable snack.",
      ],
      prep_time_min: 0,
      cook_time_min: 0,
    },
  },
  {
    name: "Rice Cake with Almond Butter",
    description:
      "A rice cake topped with a tablespoon of almond butter and banana slices.",
    calories: 200,
    protein_g: 6,
    carbs_g: 25,
    fat_g: 10,
    category: "snack",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["rice", "almonds", "banana"],
    recipe: {
      ingredients: [
        { name: "Rice cake", amount: "1", unit: "cake", category: "grains" },
        { name: "Almond butter", amount: "1", unit: "tbsp", category: "pantry" },
        { name: "Banana", amount: "1/2", unit: "sliced", category: "produce" },
      ],
      steps: [
        "Spread almond butter evenly on the rice cake.",
        "Top with banana slices and serve.",
      ],
      prep_time_min: 2,
      cook_time_min: 0,
    },
  },
  {
    name: "Edamame",
    description: "A cup of steamed edamame with a sprinkle of sea salt.",
    calories: 190,
    protein_g: 18,
    carbs_g: 14,
    fat_g: 8,
    category: "snack",
    tags: ["no_preference", "vegetarian", "vegan"],
    cuisine: "american",
    ingredient_tags: ["soy", "edamame"],
    recipe: {
      ingredients: [
        { name: "Frozen edamame (in shell)", amount: "1", unit: "cup", category: "produce" },
        { name: "Sea salt", amount: "1", unit: "pinch", category: "pantry" },
      ],
      steps: [
        "Boil edamame for 3-4 minutes or microwave according to package directions.",
        "Drain and sprinkle with sea salt.",
        "Squeeze pods to pop out the beans and enjoy.",
      ],
      prep_time_min: 1,
      cook_time_min: 4,
    },
  },
];
