import { Text } from "react-native";
import { SubScreenLayout } from "../../src/components/account/SubScreenLayout";
import {
  LongReadTitle,
  LongReadHeading,
  LongReadParagraph,
  LongReadBullet,
} from "../../src/components/account/LongRead";

export default function TermsConditions() {
  return (
    <SubScreenLayout title="Terms & Conditions">
      <LongReadTitle updated="May 21, 2026">Terms & Conditions</LongReadTitle>

      <LongReadParagraph>
        By using Revive, you agree to these terms. If you don't agree, please stop using the app and delete your account.
      </LongReadParagraph>

      <LongReadHeading>1. What Revive is</LongReadHeading>
      <LongReadParagraph>
        Revive is a fitness app that builds personalized workout and nutrition plans based on the information you share during onboarding and in your Account settings. The plans are generated by software — there is no human coach reviewing your sessions.
      </LongReadParagraph>

      <LongReadHeading>2. Not medical advice</LongReadHeading>
      <LongReadParagraph>
        Revive is not a substitute for medical care. The workouts, macros, and recommendations in the app are general guidance for healthy adults. Before starting any exercise or diet program, talk to a qualified healthcare professional — especially if you have an injury, medical condition, are pregnant, or are taking medications that affect physical performance.
      </LongReadParagraph>
      <LongReadParagraph>
        If you feel pain, dizziness, or other warning signs during a workout, stop immediately and seek medical attention.
      </LongReadParagraph>

      <LongReadHeading>3. Your account</LongReadHeading>
      <LongReadBullet>You must be 13 years or older to use Revive.</LongReadBullet>
      <LongReadBullet>Give us accurate info during onboarding — your plan only works if your inputs are honest.</LongReadBullet>
      <LongReadBullet>Keep your sign-in credentials safe. You're responsible for activity on your account.</LongReadBullet>
      <LongReadBullet>One account per person. Don't share an account between multiple users.</LongReadBullet>

      <LongReadHeading>4. License to use the app</LongReadHeading>
      <LongReadParagraph>
        We grant you a personal, non-exclusive, non-transferable, revocable license to use Revive for your own training. You may not:
      </LongReadParagraph>
      <LongReadBullet>Copy, redistribute, or resell any part of the app or its content.</LongReadBullet>
      <LongReadBullet>Reverse-engineer or scrape the app.</LongReadBullet>
      <LongReadBullet>Use the app to coach paying clients (commercial coaching tools require a separate license).</LongReadBullet>
      <LongReadBullet>Build a competing product using data extracted from the app.</LongReadBullet>

      <LongReadHeading>5. Content ownership</LongReadHeading>
      <LongReadParagraph>
        The workout plans, meal recommendations, exercise library, illustrations, and copy inside Revive are owned by us or our licensors. Your logs (sets, reps, meals you record) belong to you — we just store them.
      </LongReadParagraph>

      <LongReadHeading>6. Subscriptions and payments</LongReadHeading>
      <LongReadParagraph>
        If we introduce paid tiers, subscription terms (billing cycle, refunds, cancellation) will be disclosed at checkout. We do not auto-renew anything you didn't explicitly opt into.
      </LongReadParagraph>

      <LongReadHeading>7. Termination</LongReadHeading>
      <LongReadParagraph>
        You can delete your account anytime from the Account screen. We can suspend or terminate accounts that misuse the app — for example, attempting to break our infrastructure, harassing other users, or violating these terms. We'll usually give you notice unless the misuse is severe.
      </LongReadParagraph>

      <LongReadHeading>8. Limitation of liability</LongReadHeading>
      <LongReadParagraph>
        To the maximum extent allowed by law, Revive is provided "as is" without warranties of any kind. We're not liable for injuries, health issues, lost data, or other damages caused by using the app. Our total liability for any claim is limited to the amount you paid us in the last 12 months (or $50 if you've paid nothing).
      </LongReadParagraph>

      <LongReadHeading>9. Changes to these terms</LongReadHeading>
      <LongReadParagraph>
        We may update these terms occasionally. Material changes will be shown in-app before they take effect. Continued use of Revive after a change means you accept the new terms.
      </LongReadParagraph>

      <LongReadHeading>10. Governing law</LongReadHeading>
      <LongReadParagraph>
        These terms are governed by the laws of the jurisdiction where Revive is registered. Disputes will be resolved in the courts of that jurisdiction unless required otherwise by your local consumer-protection laws.
      </LongReadParagraph>

      <LongReadHeading>11. Contact</LongReadHeading>
      <LongReadParagraph>
        Questions about these terms — email support@revive.app.
      </LongReadParagraph>

      <Text style={{ textAlign: "center", fontSize: 11, color: "#9A9A92", marginTop: 24, marginBottom: 16 }}>
        Draft — review with legal counsel before publishing.
      </Text>
    </SubScreenLayout>
  );
}
